name: univers_app
description: A new Nowa project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  nowa_runtime: ^0.1.2
  flutter_html: ^3.0.0
  flutter_svg: ^2.2.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  dio: ^5.5.0+1
  collection: ^1.19.1
  supabase_flutter: ^2.5.3
  video_player: ^2.8.6
  chewie: ^1.8.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.0.2
  audioplayers: ^6.5.1
  flutter_tts: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
